export const surpriseMePrompts = [
  "Generate a Python function to calculate the factorial of a number.",
  "Create a JavaScript snippet to sort an array in ascending order.",
  "Write a Java program to implement a basic calculator.",
  "Generate a CSS style for a responsive navigation bar.",
  "Create a TypeScript interface for a user profile.",
  "Generate a PHP script to connect to a MySQL database.",
  "Write a C# program to check if a string is a palindrome.",
  "Create an HTML template for a contact form.",
  "Generate a Python script to fetch data from a REST API.",
  "Write a JavaScript function to validate an email address.",
  "Create a Java class for a simple shopping cart.",
  "Generate a CSS animation for a bouncing ball.",
  "Write a TypeScript function to find the maximum element in an array.",
  "Create a PHP script to upload an image to a server.",
  "Generate a C# program to implement a basic file reader.",
  "Write a Python script to extract information from a JSON file.",
  "Create a JavaScript function to shuffle an array.",
  "Generate a Java program to calculate the area of a circle.",
  "Write a CSS style for a card component.",
  "Create a TypeScript interface for a blog post.",
  "Generate a PHP script to send emails using SMTP.",
  "Write a C# program to generate a random password.",
  "Create an HTML template for a product listing.",
  "Generate a Python function to reverse a linked list.",
  "Write a JavaScript function to detect mobile device orientation.",
  "Create a Java class for a simple chat application.",
  "Generate a CSS layout for a two-column website.",
  "Write a TypeScript function to convert temperature units.",
  "Create a PHP script to generate QR codes.",
  "Generate a C# program to implement a basic quiz.",
  "Write a Python script to download images from a website.",
  "Create a JavaScript function to validate a credit card number.",
  "Generate a Java program to implement a stack data structure.",
  "Write a CSS style for a responsive image gallery.",
  "Create a TypeScript interface for a user authentication system.",
  "Generate a PHP script to parse XML data.",
  "Write a C# program to find the longest word in a sentence.",
  "Create an HTML template for a login page.",
  "Generate a Python script to scrape data from a website.",
  "Write a JavaScript function to calculate the distance between two coordinates.",
  "Create a Java class for a basic video player.",
  "Generate a CSS animation for a fading slideshow.",
  "Write a TypeScript function to filter an array based on a condition.",
  "Create a PHP script to implement user registration.",
  "Generate a C# program to implement a basic search algorithm.",
  "Write a Python script to interact with a RESTful API.",
  "Create a JavaScript function to implement a countdown timer.",
  "Generate a Java program to perform matrix multiplication.",
  "Write a CSS style for a sticky navigation bar.",
  "Create a TypeScript interface for a calendar event."
  ];