export const surpriseMePrompts = [
    "Tell me a joke.",
    "What's the weather like today?",
    "Recommend a good book to read.",
    "Teach me a new language phrase.",
    "Share a fun fact.",
    "What's the latest news?",
    "Play some relaxing music.",
    "Help me plan my day.",
    "How does photosynthesis work?",
    "Can you recommend a healthy recipe?",
    "What's the capital of France?",
    "What's the meaning of life?",
    "Translate 'Hello' into Spanish.",
    "What are the benefits of meditation?",
    "Recommend a movie to watch tonight.",
    "How do I solve a Rubik's Cube?",
    "What's the distance to the moon?",
    "What's the tallest mountain in the world?",
    "Help me brainstorm gift ideas.",
    "Tell me about artificial intelligence.",
    "How does GPS work?",
    "Teach me a magic trick.",
    "Explain the concept of black holes.",
    "What's the origin of Valentine's Day?",
    "Can you help me with a riddle?",
    "What's the best way to learn a new skill?",
    "Recommend a podcast.",
    "How do I stay motivated?",
    "What's the history of chocolate?",
    "What's the meaning of my name?",
    "Tell me a bedtime story.",
    "Recommend a good documentary.",
    "Explain the theory of relativity.",
    "What's the process of making tea?",
    "Share a historical fun fact.",
    "What are the health benefits of laughter?",
    "Help me come up with a bucket list.",
    "How do I start a small garden?",
    "What's the difference between empathy and sympathy?",
    "Recommend a travel destination.",
    "Teach me a quick workout routine.",
    "What's the best way to learn to code?",
    "Share a motivational quote.",
    "Explain the water cycle.",
    "What are some time management tips?",
    "Tell me about famous inventors.",
    "Recommend a board game.",
    "How do I improve my memory?",
    "What's the process of making ice cream?",
    "Tell me a fascinating science fact."
  ];