export const surpriseMePrompts = [
  "Create a soothing melody for relaxation",
  "Generate a high-energy beat for a workout playlist",
  "Produce a jazzy background music for a cocktail party",
  "Craft a suspenseful soundtrack for a thriller movie scene",
  "Make a futuristic and experimental electronic track",
  "Generate a cheerful and upbeat tune for a children's video",
  "Create a calming background score for a meditation session",
  "Generate a romantic melody for a love scene in a film",
  "Craft an epic and dramatic orchestral composition",
  "Produce a retro-inspired track with a vintage vibe",
  "Create a funky and groovy bassline for a dance track",
  "Generate a mysterious and ambient soundscape",
  "Make a reggae-influenced song with a laid-back rhythm",
  "Craft a traditional folk tune with acoustic instruments",
  "Produce a fast-paced and energetic video game soundtrack",
  "Generate a space-themed electronic composition",
  "Create a melancholic piano piece for a sad moment",
  "Make a lively and joyful tune for a celebration",
  "Produce a suspenseful and intense music loop",
  "Generate a cinematic score for a fantasy adventure",
  "Create a dreamy and atmospheric track",
  "Craft a happy and uplifting melody for a commercial",
  "Generate a haunting and eerie background for a horror scene",
  "Make an instrumental track with a Middle Eastern influence",
  "Produce a calming and ambient track for studying",
  "Create an energetic and dynamic rock anthem",
  "Generate a tropical and breezy summer song",
  "Craft a sophisticated jazz improvisation",
  "Make an orchestral fanfare for a grand entrance",
  "Produce a techno-infused electronic dance music (EDM) track",
  "Generate a nostalgic and retro video game theme",
  "Create a suspenseful buildup leading to a drop",
  "Make a Celtic-inspired folk melody",
  "Produce a lively and fun circus theme",
  "Generate a tribal and rhythmic percussion ensemble",
  "Craft a soulful and bluesy guitar solo",
  "Create an experimental and avant-garde composition",
  "Generate a hip-hop beat with unique samples",
  "Make a futuristic and robotic electronic track",
  "Produce a minimalistic and ambient piece",
  "Generate a country-inspired song with acoustic guitar",
  "Create an Indian classical fusion with traditional instruments",
  "Craft a motivational and inspiring anthem",
  "Make a chaotic and dissonant avant-garde piece",
  "Produce an orchestral march for a military scene",
  "Generate a playful and quirky cartoon theme",
  "Create a fast-paced and intense racing game soundtrack",
  "Craft a dream-pop song with ethereal vocals",
  "Make a suspenseful and mysterious detective theme",
  "Generate a celebratory and triumphant finale",
  ];