export const surpriseMePrompts = [
  "Create a video that simulates a day in the life of a space explorer.",
  "Generate a video of a futuristic cityscape at sunset.",
  "Make a video showing the evolution of technology from the past to the future.",
  "Create an animated video of a magical forest with talking animals.",
  "Generate a video depicting a time-traveling adventure.",
  "Make a video showcasing the beauty of underwater life in a coral reef.",
  "Create an animated video of a friendly alien visiting Earth for the first time.",
  "Generate a video visualizing a world powered entirely by renewable energy.",
  "Make a video illustrating the concept of time dilation in space.",
  "Create an animated video of a journey through a virtual reality landscape.",
  "Generate a video showcasing the wonders of a virtual art gallery.",
  "Make a video depicting a day in the life of a superhero with unique powers.",
  "Create an animated video of a steampunk-inspired city.",
  "Generate a video illustrating the process of terraforming a new planet.",
  "Make a video visualizing the exploration of an ancient, mysterious temple.",
  "Create an animated video of a futuristic sports event.",
  "Generate a video showing the construction of a megastructure in space.",
  "Make a video depicting a futuristic fashion show with innovative designs.",
  "Create an animated video of a friendly robot helping people in everyday tasks.",
  "Generate a video visualizing a world where humans coexist with intelligent dinosaurs.",
  "Make a video illustrating the concept of a parallel universe.",
  "Create an animated video of a virtual reality concert experience.",
  "Generate a video showcasing a day in the life of a character living in a cyberpunk city.",
  "Make a video visualizing the process of creating a sustainable ecosystem.",
  "Create an animated video of a time-lapse showing the growth of a futuristic city.",
  "Generate a video depicting a space battle between futuristic spacecraft.",
  "Make a video illustrating the concept of artificial intelligence in daily life.",
  "Create an animated video of a magical potion brewing in a fantasy laboratory.",
  "Generate a video showcasing the exploration of an alien planet by robotic probes.",
  "Make a video visualizing a world where animals and humans communicate.",
  "Create an animated video of a journey through a virtual reality art installation.",
  "Generate a video illustrating the concept of a floating city in the clouds.",
  "Make a video depicting the process of creating a virtual reality game.",
  "Create an animated video of a futuristic transportation system.",
  "Generate a video showing the evolution of architecture from ancient to modern.",
  "Make a video visualizing a day in the life of an advanced humanoid robot.",
  "Create an animated video of a futuristic medical breakthrough.",
  "Generate a video illustrating the concept of a time-traveling detective.",
  "Make a video depicting a day in the life of a character with shape-shifting abilities.",
  "Create an animated video of an intergalactic travel agency advertisement.",
  "Generate a video showcasing the development of a virtual reality theme park.",
  "Make a video visualizing a world where humans live alongside friendly extraterrestrials.",
  "Create an animated video of a futuristic kitchen with advanced cooking technology.",
  "Generate a video illustrating the concept of a sentient spaceship.",
  "Make a video depicting the process of building a sustainable underwater city.",
  "Create an animated video of a futuristic amusement park with holographic attractions.",
  "Generate a video showcasing the exploration of an uncharted, mystical land.",
  "Make a video visualizing a day in the life of a character with telekinetic powers.",
  "Create an animated video of a futuristic wildlife documentary.",
  "Generate a video illustrating the concept of a floating, self-sustainable island,"
];